AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SES Email Handler Lambda - Process emails from SES via SQS

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Tracing: Active
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Resources:
  # SES Email Handler Lambda Function
  SESEmailHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ses-email-handler-${Environment}
      CodeUri: src/
      Handler: sqs_email_handler.lambda_handler
      Description: Process emails from SES via SQS
      Environment:
        Variables:
          SES_EMAIL_BUCKET: !Ref SESEmailBucket

      # SQS Event Source
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EmailQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures

      # IAM Permissions
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${SESEmailBucket}/*
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !GetAtt EmailQueue.Arn
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource: '*'

  # SQS Queue for SES notifications
  EmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ses-email-queue-${Environment}
      VisibilityTimeout: 180  # 6x Lambda timeout (30s * 6)
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EmailDLQ.Arn
        maxReceiveCount: 3

  # Dead Letter Queue for failed messages
  EmailDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ses-email-dlq-${Environment}
      MessageRetentionPeriod: 1209600  # 14 days

  # SQS Queue Policy (allows SES to send messages)
  EmailQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref EmailQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt EmailQueue.Arn
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId

  # S3 Bucket for SES emails
  SESEmailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ses-emails-${AWS::AccountId}-${Environment}
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldEmails
            Status: Enabled
            ExpirationInDays: 30  # Keep emails for 30 days

  # Allow SES to write to S3
  SESEmailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SESEmailBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Principal:
              Service: ses.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub ${SESEmailBucket.Arn}/*
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId

Outputs:
  SESEmailHandlerFunctionName:
    Description: SES Email Handler Lambda Function Name
    Value: !Ref SESEmailHandlerFunction
    Export:
      Name: !Sub ${AWS::StackName}-FunctionName

  SESEmailHandlerFunctionArn:
    Description: SES Email Handler Lambda Function ARN
    Value: !GetAtt SESEmailHandlerFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn

  EmailQueueUrl:
    Description: SQS Queue URL for email processing
    Value: !Ref EmailQueue
    Export:
      Name: !Sub ${AWS::StackName}-EmailQueueUrl

  EmailQueueArn:
    Description: SQS Queue ARN (use this in SES Receipt Rule)
    Value: !GetAtt EmailQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}-EmailQueueArn

  SESEmailBucketName:
    Description: S3 Bucket for SES emails (use this in SES Receipt Rule)
    Value: !Ref SESEmailBucket
    Export:
      Name: !Sub ${AWS::StackName}-SESEmailBucketName
